spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI}
server:
  port: 8080


clientes-service:
  url: http://cliente-service:8082

contenedor-service:
  url: http://contenedor-service:8083

solicitud-service:
  url: http://solicitud-service:8084