spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI}
server:
  port: 8080

clientes-service:
  url: http://cliente-service:8081

contenedor-service:
  url: http://contenedor-service:8082

solicitud-service:
  url: http://solicitud-service:8084

  cloud:
    gateway:
      routes:
        - id: geo-service
          uri: http://geo-service:8088
          predicates:
            - Path=/geo/**