spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/tpi-backend
server:
  port: 8080

clientes-service:
  url: http://localhost:8081

solicitudes-service:
  url: http://localhost:8082

keycloak:
  url: http://localhost:8180
