server:
  port: 8083

spring:
  application:
    name: solicitud-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

cliente-service:
  url: http://cliente-service:8081/api/clientes
contenedor-service:
    url: http://contenedor-service:8082/api/contenedores
tarifa-service:
  url: http://tarifa-service:8087/api/tarifas
ruta-service:
  url: http://ruta-service:8086/api/rutas
